// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enzyewybberxgpmgixib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuenlld3liYmVyeGdwbWdpeGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NDE3NDEsImV4cCI6MjA1NjQxNzc0MX0._bsFbE_1g0Yq4XWG59HqEveEeFHtfzndU_Sq5ACdDVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);